# Generated by Django 4.2.6 on 2023-10-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='finished_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='level',
            field=models.CharField(choices=[('internship', 'Iinternship'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=10),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume')),
            ],
        ),
    ]
